"""PersonaService — generates an agent persona (人格画像) for each post.

Each office gets a named, characterful person: name + courtesy name (字),
temperament, governing style, and a brief origin. Generated by the LLM so
every court is fresh; regenerated on appointment/removal (new person in
the office).

Persona is stored as JSON in posts.persona. If no LLM is available, a
deterministic template fallback keeps the system usable offline.
"""
from __future__ import annotations

import json
from typing import Any

from imperial.institution import Institution
from imperial.storage import Storage

_PERSONA_PROMPT = """你是帝国吏部的人事官，为一位新任官员拟写人格画像。
岗位：{title}（{post_id}），职掌：{role_desc}
请用中文拟写，严格输出 JSON（不要多余文字）：
{{
  "name": "姓名（古风，两到三字）",
  "courtesy": "字（一个字或两字）",
  "temperament": "性格（20字内，与岗位匹配）",
  "style": "施政风格（20字内）",
  "origin": "出身履历（40字内，如科举/世家/边功）"
}}
约束：姓氏必须从下列姓氏池中选择，且不得使用已用姓氏 {used_surnames}：
{姓氏池}
"""

_SURNAME_POOL = "王 李 张 刘 陈 杨 赵 黄 周 吴 徐 孙 马 朱 胡 郭 何 高 林 罗 郑 梁 谢 宋 唐 许 韩 冯 邓 曹 彭 曾 萧 田 董 潘 袁 蒋 蔡 余 杜 叶 程 苏 魏 吕 丁 任 卢 姚 姜 崔 钟 谭 陆 范 汪 廖 石 金 韦 贾 夏 傅 方 邹 熊 白 孟 秦 邱 侯 江 尹 薛 段 雷 龙 黎 史 陶 贺 毛 郝 顾 龚 邵 万 钱 严 覃 武 戴 莫 孔 向 常 温 康 施 文 牛 樊 葛 邢 齐 安 洪 鲁 伍 季 欧阳 慕容 上官 司马"

_ROLE_HINTS = {
    "coordinator": "统筹百官、运筹帷幄",
    "executor": "任事干练、踏实办差",
    "inspector": "刚直不阿、明察秋毫",
    "inspector_assistant": "机敏审慎、秉公取证",
    "external": "长于辞令、折冲樽俎",
}

_FALLBACK_NAMES = ["沈观澜", "裴长策", "顾明远", "谢清和", "陆衡之", "韩守拙", "柳文昭", "楚怀瑾"]


class PersonaService:
    def __init__(self, storage: Storage, llm: Any | None = None):
        self.storage = storage
        self.llm = llm  # LLMClient or None (offline fallback)

    # ── generation ─────────────────────────────────────────
    def generate(
        self,
        institution: Institution,
        post_id: str,
        used_surnames: set[str] | None = None,
    ) -> dict[str, str]:
        """Generate a persona. `used_surnames` forces surname diversity.

        Tries the LLM (if present) with the constraint; validates the surname
        is new; retries a few times; falls back to the template pool.
        """
        post = institution.post(post_id)
        used = used_surnames or set()
        role_desc = _ROLE_HINTS.get(post.role, "各司其职")
        if self.llm is not None:
            for _ in range(3):
                prompt = _PERSONA_PROMPT.format(
                    title=post.title, post_id=post.id, role_desc=role_desc,
                    used_surnames="、".join(sorted(used)) if used else "无",
                    姓氏池=_SURNAME_POOL,
                )
                try:
                    resp = self.llm.complete(
                        [{"role": "user", "content": prompt}],
                    )
                    persona = self._parse(resp.content or "")
                except Exception:  # noqa: BLE001 — network hiccup → retry/fallback
                    persona = None
                if persona and (not used or self._surname(persona["name"]) not in used):
                    return persona
        return self._fallback(used)

    def regenerate(
        self,
        institution: Institution,
        post_id: str,
        used_surnames: set[str] | None = None,
    ) -> dict[str, str]:
        """New person in the office (after removal/appointment)."""
        return self.generate(institution, post_id, used_surnames)

    # ── persistence ────────────────────────────────────────
    def save(self, post_id: str, persona: dict[str, str]) -> None:
        self.storage.execute(
            "UPDATE posts SET persona = ? WHERE id = ?",
            (json.dumps(persona, ensure_ascii=False), post_id),
        )

    def load(self, post_id: str) -> dict[str, str] | None:
        row = self.storage.query_one("SELECT persona FROM posts WHERE id = ?", (post_id,))
        if row is None or not row.get("persona"):
            return None
        try:
            return json.loads(row["persona"])
        except json.JSONDecodeError:
            return None

    # ── helpers ────────────────────────────────────────────
    @staticmethod
    def _surname(name: str) -> str:
        """Extract the surname (first char; compound surnames handled)."""
        for s in ("欧阳", "慕容", "上官", "司马", "夏侯", "诸葛"):
            if name.startswith(s):
                return s
        return name[0] if name else ""

    @staticmethod
    def _parse(content: str) -> dict[str, str] | None:
        import re

        m = re.search(r"\{.*\}", content, re.DOTALL)
        if not m:
            return None
        try:
            data = json.loads(m.group(0))
        except json.JSONDecodeError:
            return None
        if not all(k in data for k in ("name", "courtesy", "temperament", "style", "origin")):
            return None
        return {k: str(data[k]) for k in ("name", "courtesy", "temperament", "style", "origin")}

    @staticmethod
    def _fallback(used: set[str] | None = None) -> dict[str, str]:
        """Template persona with a surname not already in use."""
        used = used or set()
        for name in _FALLBACK_NAMES:
            if PersonaService._surname(name) not in used:
                courtesy = name[-1] + "之"
                return {
                    "name": name,
                    "courtesy": courtesy,
                    "temperament": "持重端方",
                    "style": "秉公持正，雷厉风行",
                    "origin": "以贤良方正举荐入仕",
                }
        # all surnames taken — allow repeat (extremely unlikely with 8 posts)
        name = _FALLBACK_NAMES[0]
        return {
            "name": name,
            "courtesy": name[-1] + "之",
            "temperament": "持重端方",
            "style": "秉公持正，雷厉风行",
            "origin": "以贤良方正举荐入仕",
        }
