"""PersonaService — generates an agent persona (人格画像) for each post.

Each office gets a named, characterful person: name + courtesy name (字),
temperament, governing style, and a brief origin. Generated by the LLM so
every court is fresh; regenerated on appointment/removal (new person in
the office).

Persona is stored as JSON in posts.persona. If no LLM is available, a
deterministic template fallback keeps the system usable offline.
"""
from __future__ import annotations

import json
import random
from typing import Any

from imperial.institution import Institution
from imperial.storage import Storage

_PERSONA_PROMPT = """你是帝国吏部的人事官，为一位新任官员拟写人格画像。
岗位：{title}（{post_id}），职掌：{role_desc}
请用中文拟写，严格输出 JSON（不要多余文字）：
{{
  "name": "姓名（古风，两到三字）",
  "courtesy": "字（一个字或两字）",
  "temperament": "性格（20字内，与岗位匹配）",
  "style": "施政风格（20字内）",
  "origin": "出身履历（40字内，如科举/世家/边功）"
}}
"""

_ROLE_HINTS = {
    "coordinator": "统筹百官、运筹帷幄",
    "executor": "任事干练、踏实办差",
    "inspector": "刚直不阿、明察秋毫",
    "inspector_assistant": "机敏审慎、秉公取证",
    "external": "长于辞令、折冲樽俎",
}

_FALLBACK_NAMES = ["沈观澜", "裴长策", "顾明远", "谢清和", "陆衡之", "韩守拙", "柳文昭", "楚怀瑾"]

_FALLBACK_STYLES = ["秉公持正，雷厉风行", "温和务实，步步为营", "峻切刚毅，执法如山", "沉稳老练，深谋远虑"]


class PersonaService:
    def __init__(self, storage: Storage, llm: Any | None = None):
        self.storage = storage
        self.llm = llm  # LLMClient or None (offline fallback)

    # ── generation ─────────────────────────────────────────
    def generate(self, institution: Institution, post_id: str) -> dict[str, str]:
        post = institution.post(post_id)
        role_desc = _ROLE_HINTS.get(post.role, "各司其职")
        prompt = _PERSONA_PROMPT.format(title=post.title, post_id=post.id, role_desc=role_desc)
        if self.llm is not None:
            try:
                resp = self.llm.complete(
                    [{"role": "user", "content": prompt}],
                )
                persona = self._parse(resp.content or "")
                if persona:
                    return persona
            except Exception:  # noqa: BLE001 — fall back to template
                pass
        return self._fallback(post_id)

    def regenerate(self, institution: Institution, post_id: str) -> dict[str, str]:
        """New person in the office (after removal/appointment)."""
        return self.generate(institution, post_id)

    # ── persistence ────────────────────────────────────────
    def save(self, post_id: str, persona: dict[str, str]) -> None:
        self.storage.execute(
            "UPDATE posts SET persona = ? WHERE id = ?",
            (json.dumps(persona, ensure_ascii=False), post_id),
        )

    def load(self, post_id: str) -> dict[str, str] | None:
        row = self.storage.query_one("SELECT persona FROM posts WHERE id = ?", (post_id,))
        if row is None or not row.get("persona"):
            return None
        try:
            return json.loads(row["persona"])
        except json.JSONDecodeError:
            return None

    # ── helpers ────────────────────────────────────────────
    @staticmethod
    def _parse(content: str) -> dict[str, str] | None:
        import re

        m = re.search(r"\{.*\}", content, re.DOTALL)
        if not m:
            return None
        try:
            data = json.loads(m.group(0))
        except json.JSONDecodeError:
            return None
        if not all(k in data for k in ("name", "courtesy", "temperament", "style", "origin")):
            return None
        return {k: str(data[k]) for k in ("name", "courtesy", "temperament", "style", "origin")}

    @staticmethod
    def _fallback(post_id: str) -> dict[str, str]:
        name = random.choice(_FALLBACK_NAMES)
        courtesy = name[-1] + "之"
        return {
            "name": name,
            "courtesy": courtesy,
            "temperament": "持重端方",
            "style": random.choice(_FALLBACK_STYLES),
            "origin": "以贤良方正举荐入仕",
        }
