import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/api";
import type { Impeachment } from "../lib/api";

export function CensoratePage() {
  const qc = useQueryClient(); const { data: overview } = useQuery({ queryKey: ["censorate", "overview"], queryFn: () => api.censorateOverview() }); const { data: impeachments } = useQuery({ queryKey: ["impeachments"], queryFn: () => api.listImpeachments() });
  const verdict = useMutation({ mutationFn: ({ id, v }: { id: string; v: string }) => api.verdictImpeachment(id, v, "朱批"), onSuccess: () => { qc.invalidateQueries({ queryKey: ["impeachments"] }); qc.invalidateQueries({ queryKey: ["censorate"] }); qc.invalidateQueries({ queryKey: ["posts"] }); } });
  return <section><div className="page-heading"><div><div className="eyebrow">御史台 · CENSORATE</div><h2>御史台案卷</h2><p>明察百官违制，候陛下裁决。</p></div><span className="seal">执法<br />如山</span></div>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))", gap: 10, marginBottom: 34 }}>{[["在审案件", overview?.pending_impeachments], ["待裁决", overview?.pending_verdicts], ["近期违制", overview?.recent_violations], ["已发警告", overview?.warnings_issued], ["已革职", overview?.removals]].map(([label, value]) => <div className="panel" key={label as string} style={{ padding: "15px 10px", textAlign: "center" }}><div style={{ fontSize: "1.7rem", color: "#8b1a1a" }}>{value ?? 0}</div><div style={{ color: "#806e5d", fontSize: ".78rem" }}>{label}</div></div>)}</div>
    <div className="eyebrow" style={{ marginBottom: 12 }}>在审案卷 · PENDING CASES</div>{impeachments?.length === 0 && <div className="panel" style={{ padding: 40, textAlign: "center", color: "#806e5d" }}>海晏河清，暂无弹劾案卷。</div>}{impeachments?.map((imp: Impeachment) => <article className="paper" key={imp.id} style={{ padding: "21px 24px 21px 30px", marginBottom: 16 }}><header style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}><strong style={{ fontSize: "1.12rem" }}>弹劾 · {imp.target_post_title ?? imp.target_post}</strong><span style={{ color: imp.status === "pending" ? "#8b1a1a" : "#796d63", fontSize: ".8rem" }}>{imp.status}</span></header><p style={{ margin: "14px 0 8px", lineHeight: 1.8 }}><b>案由：</b>{imp.evidence}</p>{imp.brief && <p style={{ color: "#796d63", fontSize: ".92rem", lineHeight: 1.7 }}><b>调查简报：</b>{imp.brief}</p>}{imp.recommendation && <p style={{ margin: "12px 0", color: "#604d3c" }}>御史台拟议：<strong style={{ color: imp.recommendation === "removal" ? "#8b1a1a" : "#a67c00" }}>{imp.recommendation === "removal" ? "革职查办" : "留任警告"}</strong></p>}{imp.status === "pending" && imp.recommendation && <div style={{ display: "flex", gap: 8, marginTop: 15, borderTop: "1px solid #b7884828", paddingTop: 14 }}><button className="action-btn" onClick={() => verdict.mutate({ id: imp.id, v: "approve" })} disabled={verdict.isPending}>朱批 · 准奏</button><button className="action-btn gold" onClick={() => verdict.mutate({ id: imp.id, v: "reject" })} disabled={verdict.isPending}>朱批 · 驳回</button></div>}{imp.verdict && <div className="verdict-ink" style={{ marginTop: 13 }}>裁决：{imp.verdict}</div>}</article>)}</section>;
}
