import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/api";
import type { Post } from "../lib/api";

const ROLE_LABELS: Record<string, string> = { coordinator: "总协调", executor: "执行", inspector: "监察", inspector_assistant: "监察助手", external: "对外" };
const STATUS_LABELS: Record<string, string> = { active: "在职", vacant: "空缺", removed: "革职" };

export function PostsPage() {
  const qc = useQueryClient(); const { data: posts } = useQuery({ queryKey: ["posts"], queryFn: () => api.listPosts() }); const [agentName, setAgentName] = useState<Record<string, string>>({});
  const appoint = useMutation({ mutationFn: ({ id, agent }: { id: string; agent: string }) => api.appointPost(id, agent), onSuccess: () => qc.invalidateQueries({ queryKey: ["posts"] }) });
  return <section><div className="page-heading"><div><div className="eyebrow">百官 · OFFICES</div><h2>官职墙</h2><p>百官各司其职，空缺待诏任命。</p></div><span className="seal">百官<br />名录</span></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(235px, 1fr))", gap: 16 }}>{posts?.map((p: Post) => <article className="panel" key={p.id} style={{ padding: "20px", borderColor: p.status === "vacant" ? "#a67c00" : p.status === "removed" ? "#aaa" : "#8b1a1a66", borderStyle: p.status === "vacant" ? "dashed" : "solid", opacity: p.status === "removed" ? .68 : 1 }}><header style={{ display: "flex", justifyContent: "space-between", alignItems: "start", gap: 8 }}><div><div className="eyebrow">{ROLE_LABELS[p.role] ?? p.role}</div><h3 style={{ margin: "5px 0 0", fontSize: "1.35rem" }}>{p.title}</h3></div><span style={{ color: p.status === "vacant" ? "#a67c00" : p.status === "removed" ? "#777" : "#8b1a1a", fontSize: ".78rem" }}>{STATUS_LABELS[p.status] ?? p.status}</span></header><div style={{ margin: "20px 0", padding: "13px", background: "#f6ecde", color: "#604d3c", fontSize: ".82rem", lineHeight: 1.8 }}>官署：{p.id}<br />品秩：{p.model ?? "待定"}{p.reports_to && <><br />隶属：{p.reports_to}</>}{p.current_agent && <><br />现任：{p.current_agent}</>}</div>{p.status === "vacant" && <div style={{ display: "flex", gap: 7 }}><input aria-label={`${p.title}任命人选`} placeholder="agent 名（可留空）" value={agentName[p.id] ?? ""} onChange={e => setAgentName(s => ({ ...s, [p.id]: e.target.value }))} style={{ minWidth: 0, flex: 1, padding: "9px", border: "1px solid #c5a57999", background: "#fffdf9" }} /><button className="action-btn" onClick={() => appoint.mutate({ id: p.id, agent: agentName[p.id] || `agent_${p.id}` })} disabled={appoint.isPending}>任命</button></div>}</article>)}</div></section>;
}
